# Generated by Django 2.2 on 2020-08-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('text', models.TextField()),
                ('price', models.DecimalField(decimal_places=3, max_digits=25)),
                ('image1', models.ImageField(blank=True, upload_to='media/static')),
                ('image2', models.ImageField(blank=True, upload_to='media/static')),
            ],
        ),
    ]
