# Generated by Django 2.2 on 2020-08-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='location',
            field=models.TextField(null=True),
        ),
    ]
