# Generated by Django 2.2 on 2020-08-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_package_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_food', models.TextField()),
                ('travel_news', models.TextField()),
                ('modern_tech', models.TextField()),
                ('product', models.TextField()),
                ('health_care', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='package',
            name='image1',
            field=models.ImageField(blank=True, upload_to='service'),
        ),
        migrations.AlterField(
            model_name='package',
            name='image2',
            field=models.ImageField(blank=True, upload_to='service'),
        ),
    ]
