# Generated by Django 2.2 on 2020-08-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20200813_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='blog')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('text', models.TextField()),
                ('image1', models.ImageField(blank=True, upload_to='blog')),
                ('image2', models.ImageField(blank=True, upload_to='blog')),
            ],
        ),
    ]
