# Generated by Django 2.2 on 2020-08-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_about_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalGuest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=250)),
                ('text', models.TextField()),
            ],
        ),
    ]
