# Generated by Django 2.2 on 2020-08-21 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0010_auto_20200820_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='toursitblog',
            name='photo',
            field=models.ImageField(null=True, upload_to='blog'),
        ),
    ]
